name: "CI"

on:
   push:
      branches:
        - main
  
jobs:
  testeCI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      
      - name: Run Script
        run: echo "ate aqui deu certo"
        
