name: testeCI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
 jobs:
  testeCI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
       
      - name: HTTP Server Action
        uses: Eun/http-server-action@v1.0.6
        
      - name: Print
        run:
          echo "deu certo ate aqui!"
  
