name: testeCI

on:
  push:
    branches: 
      main
    
  workflow_dispatch:  
    
        
jobs:
  testeCI: 
    build:
     runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Rodar script
    - run: 
        echo "deu certo aqui".
  
 
